"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import { queryContents, queryDashboard, queryEvidences, queryIntegrationMatrix, queryItems, type RadarItem } from "../lib/radar/queries";
import { sectors as sectorCatalog } from "../config/sectors";
import { demoData } from "../lib/demo/data";
import type { User } from "../types";

export function ModuleHeader({eyebrow,title,text}:{eyebrow:string;title:string;text:string}) {
  return <section className="page-title"><span className="eyebrow"><i/> {eyebrow}</span><div><h1>{title}</h1></div><p>{text}</p></section>;
}
export function KpiCard({label,value,tone=""}:{label:string;value:string|number;tone?:string}) {
  return <article className={`kpi ${tone}`}><strong>{value}</strong><p>{label}</p></article>;
}
export function EmptyState({title,text,action}:{title:string;text:string;action?:React.ReactNode}) {
  return <div className="context-empty"><i>⌁</i><div><b>{title}</b><p>{text}</p></div>{action}</div>;
}
export function StatusBadge({value}:{value:string}) {return <span className="data-badge status-data">{value.replaceAll("_"," ")}</span>}
export function PriorityBadge({value}:{value:string}) {return <span className={`data-badge priority-${value.toLowerCase()}`}>{value}</span>}
export function ItemTable({items,onOpen}:{items:RadarItem[];onOpen?:(id:string)=>void}) {
  return <div className="real-table"><div className="real-table-head"><span>ITEM</span><span>SETOR</span><span>ESCOLA</span><span>PRIORIDADE</span><span>STATUS</span></div>{items.length?items.map(item=><button className="real-table-row" key={item.id} onClick={()=>onOpen?.(item.id)}><span><b>{item.title}</b><small>{item.record_type} · {item.demand_categories?.name||"Sem categoria"}</small></span><span>{item.sectors?.code||"—"}</span><span>{item.schools?.name||"Regional"}</span><PriorityBadge value={item.priority}/><StatusBadge value={item.status}/></button>):<EmptyState title="Nenhum item encontrado" text="Não existem registros autorizados para os filtros atuais."/>}</div>;
}
export function DataProvenanceReal({source="Supabase RADAR 360"}:{source?:string}) {
  return <div className="provenance"><span><b>Fonte</b>{source}</span><span><b>Responsável</b>URE Guarulhos Sul</span><span><b>Acesso</b>Perfil + RLS</span><span><b>Integração</b>Dados institucionais reais</span></div>;
}

export function Radar360Module({user,go}:{user:User;go:(path:string)=>void}) {
  const [sectors,setSectors]=useState<any[]>([]);const [items,setItems]=useState<RadarItem[]>([]);const [hubs,setHubs]=useState<any[]>([]);
  useEffect(()=>{if(user.role==="VISITANTE")return;queueMicrotask(async()=>{const supabase=getSupabaseBrowserClient();const [{data:sectorData},{data:itemData},{data:hubData}]=await Promise.all([supabase.from("sectors").select("id,code,slug,name,description").eq("active",true).order("code"),queryItems(supabase,{limit:500}),supabase.from("hubs").select("id,sector_id,status").eq("active",true)]);setSectors(sectorData??[]);setItems(itemData);setHubs(hubData??[])})},[user.id,user.role]);
  const shownSectors=user.role==="VISITANTE"?sectorCatalog.filter(s=>s.shortName!=="GAB").map(s=>({id:s.shortName,code:s.shortName,slug:s.slug,name:s.name,description:s.description})):sectors;
  const shownHubs=user.role==="VISITANTE"?["SETEC","SEOM","ESE"].map(sector_id=>({sector_id,status:"DEMO"})):hubs;
  return <><ModuleHeader eyebrow="ECOSSISTEMA INTEGRADO" title="RADAR 360" text="Visão transversal dos setores, prioridades, escolas e integrações autorizadas."/><div className="sector-overview-grid">{shownSectors.map(s=>{const own=items.filter(i=>i.sector_id===s.id);return <button className={`sector-overview-card ${user.sectorId===s.id?"highlight":""}`} key={s.id} onClick={()=>go(`/radar360/setores/${s.slug}`)}><span>{s.code}</span><h3>{s.name}</h3><p>{s.description}</p><div><b>{user.role==="VISITANTE"?"—":own.filter(i=>!["CONCLUIDA","CANCELADA"].includes(i.status)).length}</b> ativos <b>{user.role==="VISITANTE"?"—":own.filter(i=>i.record_type==="PENDENCIA").length}</b> pendências</div><footer>{shownHubs.some(h=>h.sector_id===s.id)?"Hub disponível":"Em implantação"} <strong>→</strong></footer></button>})}</div><DataProvenanceReal source={user.role==="VISITANTE"?"Base demonstrativa local":"Supabase RADAR 360"}/></>;
}

export function BigModule() {
  const [sources,setSources]=useState<any[]>([]);
  useEffect(()=>{queueMicrotask(async()=>{const {data}=await getSupabaseBrowserClient().from("data_sources").select("id,name,source_type,status,last_updated_at,sectors(code,name)").eq("active",true).order("name");setSources(data??[])})},[]);
  return <><ModuleHeader eyebrow="INTELIGÊNCIA DE DADOS" title="BIGuarulhosSul" text="Camada preparada para dashboards, indicadores, relatórios e fontes autorizadas."/><section className="panel"><header><div><span className="section-label">FONTES DE DADOS</span><h2>Integrações analíticas</h2></div></header>{sources.length?<div className="simple-list">{sources.map(s=><div key={s.id}><b>{s.name}</b><span>{s.source_type} · {s.status}</span><small>{s.sectors?.code||"Regional"} · {s.last_updated_at?new Date(s.last_updated_at).toLocaleDateString("pt-BR"):"Sem atualização registrada"}</small></div>)}</div>:<EmptyState title="Fonte ainda não integrada" text="Nenhuma fonte analítica foi autorizada para o BIGuarulhosSul."/>}</section><DataProvenanceReal source="Cadastro de fontes do Supabase"/></>;
}

export function MdiModule() {
  const [data,setData]=useState<any>({sectors:[],hubs:[],agreements:[],sources:[]});const [shared,setShared]=useState<RadarItem[]>([]);
  useEffect(()=>{queueMicrotask(async()=>{const supabase=getSupabaseBrowserClient();const [matrix,items]=await Promise.all([queryIntegrationMatrix(supabase),queryItems(supabase,{limit:200})]);setData(matrix);setShared(items.data.filter(i=>["PUBLICO","GESTAO","ESCOLAS"].includes(i.visibility)))})},[]);
  return <><ModuleHeader eyebrow="LEITURA INTEGRADA" title="Integração! Painel MDI" text="Leitura transversal baseada nas fontes, hubs e compartilhamentos já autorizados."/><div className="kpi-grid"><KpiCard label="Setores participantes" value={data.sectors.length}/><KpiCard label="Itens compartilhados" value={shared.length}/><KpiCard label="Fontes cadastradas" value={data.sources.length}/><KpiCard label="Integrações existentes" value={data.hubs.length}/></div><section className="panel"><header><div><span className="section-label">INDICADORES TRANSVERSAIS</span><h2>Itens institucionais compartilhados</h2></div></header><ItemTable items={shared.slice(0,12)}/></section><DataProvenanceReal/></>;
}

export function CommunicaModule({user}:{user:User}) {
  const [items,setItems]=useState<any[]>([]);
  useEffect(()=>{queueMicrotask(async()=>{const {data}=await queryContents(getSupabaseBrowserClient());setItems(data)})},[user.id]);
  return <><ModuleHeader eyebrow="COMUNICA! INSTITUCIONAL" title="Conteúdos institucionais" text="Comunicados, orientações, documentos, links e avisos autorizados."/><div className="content-grid">{items.length?items.map(x=><article className="content-card" key={x.id}><StatusBadge value={x.content_type}/><h3>{x.title}</h3><p>{x.content||"Conteúdo disponível no link institucional."}</p><small>{x.sectors?.code||"Regional"} · {new Date(x.published_at||x.created_at).toLocaleDateString("pt-BR")}</small>{x.external_url&&<a href={x.external_url} target="_blank" rel="noopener noreferrer">Abrir conteúdo ↗</a>}</article>):<EmptyState title="Nenhum conteúdo institucional publicado" text="Comunicados e orientações aparecerão aqui após publicação autorizada."/>}</div><DataProvenanceReal/></>;
}

export function EvidenceModule({user}:{user:User}) {
  const [evidences,setEvidences]=useState<any[]>([]);const [items,setItems]=useState<RadarItem[]>([]);const [comments,setComments]=useState<any[]>([]);const [open,setOpen]=useState(false);const [message,setMessage]=useState("");const [draft,setDraft]=useState({itemId:"",title:"",description:"",type:"REGISTRO",url:"",visibility:"GESTAO"});
  const load=async()=>{const supabase=getSupabaseBrowserClient();const [{data},{data:itemData},{data:commentData}]=await Promise.all([queryEvidences(supabase),queryItems(supabase,{limit:200}),supabase.from("institutional_item_comments").select("id,item_id,content,visibility,created_at,institutional_items(title)").order("created_at",{ascending:false}).limit(100)]);setEvidences(data);setItems(itemData);setComments(commentData??[])};
  useEffect(()=>{queueMicrotask(()=>void load())},[user.id]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();const item=items.find(i=>i.id===draft.itemId);const supabase=getSupabaseBrowserClient();const {data:{user:authUser}}=await supabase.auth.getUser();if(!item||!authUser)return;const {error}=await supabase.from("evidences").insert({organization_id:item.organization_id,item_id:item.id,sector_id:item.sector_id,school_id:item.school_id,title:draft.title,description:draft.description||null,evidence_type:draft.type,external_url:draft.url||null,visibility:draft.visibility,created_by:authUser.id});setMessage(error?"A evidência não pôde ser registrada para este perfil.":"Evidência registrada com sucesso.");if(!error){setOpen(false);await load()}};
  return <><ModuleHeader eyebrow="ACOMPANHAMENTO" title="Evidências e devolutivas" text="Registros reais associados aos itens institucionais e filtrados pela RLS."/><div className="toolbar">{user.role!=="ESCOLA"&&<button className="add-user evidence-add" onClick={()=>setOpen(v=>!v)}>{open?"Cancelar":"+ Nova evidência"}</button>}</div>{open&&<form className="user-form evidence-form" onSubmit={submit}><label>Item institucional<select value={draft.itemId} onChange={e=>setDraft({...draft,itemId:e.target.value})} required><option value="">Selecione</option>{items.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>Título<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} required/></label><label>Tipo<input value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})} required/></label><label>URL externa<input type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})}/></label><label>Visibilidade<select value={draft.visibility} onChange={e=>setDraft({...draft,visibility:e.target.value})}>{["PUBLICO","ESCOLAS","GESTAO","RESTRITO_SETOR","RESTRITO_REGIONAL"].map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Descrição<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><button>Registrar evidência</button></form>}{message&&<div className="inline-message login-success">{message}</div>}<div className="evidence-grid">{evidences.length?evidences.map(e=><article className="evidence-card" key={e.id}><span>{e.evidence_type}</span><h3>{e.title}</h3><p>{e.description||"Evidência vinculada sem descrição textual."}</p><small>{e.sectors?.code||"—"} · {e.schools?.name||"Regional"} · {new Date(e.created_at).toLocaleDateString("pt-BR")}</small>{e.external_url&&<a href={e.external_url} target="_blank" rel="noopener noreferrer">Abrir evidência ↗</a>}</article>):<EmptyState title={`Nenhuma evidência registrada${user.role==="GESTAO"?` para ${user.institutionalProfileName||"este setor"}`:""}.`} text="Use “Nova evidência” quando houver um registro autorizado para documentar."/>}</div><section className="panel feedback-panel"><header><div><span className="section-label">DEVOLUTIVAS</span><h2>Comentários institucionais</h2></div></header>{comments.length?<div className="simple-list">{comments.map(c=><div key={c.id}><b>{c.institutional_items?.title||"Item institucional"}</b><span>{c.content}</span><small>{new Date(c.created_at).toLocaleString("pt-BR")} · {c.visibility}</small></div>)}</div>:<EmptyState title="Nenhuma devolutiva registrada" text="Comentários associados aos itens aparecerão nesta seção."/>}</section><DataProvenanceReal/></>;
}

export function ExecutiveModule({user,mode}:{user:User;mode:"ADMIN"|"GESTAO"}) {
  const [items,setItems]=useState<RadarItem[]>([]);const [base,setBase]=useState<any>({schools:0,sectors:0,evidences:0,hubs:[]});
  useEffect(()=>{if(user.role==="VISITANTE")return;queueMicrotask(async()=>{const data=await queryDashboard(getSupabaseBrowserClient());setItems(data.items);setBase(data)})},[user.id,user.role]);
  if(user.role==="VISITANTE")return <><ModuleHeader eyebrow="INDICADORES DEMONSTRATIVOS" title="Painel de indicadores Demo" text="Simulação local e isolada, sem consulta ao banco institucional."/><div className="auth-notice"><i>◎</i><div><b>Dados totalmente fictícios</b><p>Os indicadores abaixo existem apenas para demonstrar a experiência do RADAR 360.</p></div><span>DEMO ISOLADO</span></div><div className="kpi-grid">{demoData.kpis.map(card=><KpiCard key={card.label} label={card.label} value={card.value} tone={card.tone}/>)}</div><DataProvenanceReal source="Base demonstrativa local"/></>;
  const today=new Date().toISOString().slice(0,10);const relevant=mode==="GESTAO"&&user.sectorId?items.filter(i=>i.sector_id===user.sectorId):items;const cards=[["Itens ativos",relevant.filter(i=>!["CONCLUIDA","CANCELADA"].includes(i.status)).length],["Demandas",relevant.filter(i=>i.record_type==="DEMANDA").length],["Pendências",relevant.filter(i=>i.record_type==="PENDENCIA").length],["Críticos",relevant.filter(i=>i.priority==="CRITICA").length],["Vencidos",relevant.filter(i=>i.due_date&&i.due_date<today&&!["CONCLUIDA","CANCELADA"].includes(i.status)).length],["Concluídos",relevant.filter(i=>i.status==="CONCLUIDA").length]];
  return <><ModuleHeader eyebrow={mode==="ADMIN"?"VISÃO EXECUTIVA REGIONAL":"MEU SETOR"} title={mode==="ADMIN"?"Painel da Dirigente":"Painel da Gestão"} text={mode==="ADMIN"?"Panorama real da URE Guarulhos Sul.":"Ambiente operacional do setor autenticado."}/><div className="sector-stat-grid">{cards.map(([l,v])=><KpiCard key={String(l)} label={String(l)} value={v}/>)}</div>{mode==="ADMIN"&&<div className="kpi-grid compact-kpis"><KpiCard label="Escolas" value={base.schools}/><KpiCard label="Setores" value={base.sectors}/><KpiCard label="Evidências" value={base.evidences}/><KpiCard label="Hubs" value={base.hubs.length}/></div>}<section className="panel"><header><div><span className="section-label">ITENS RECENTES</span><h2>Prioridades em acompanhamento</h2></div></header><ItemTable items={relevant.slice(0,15)}/></section><DataProvenanceReal/></>;
}

export function IntegrationMatrixModule() {
  const [data,setData]=useState<any>({sectors:[],hubs:[],agreements:[],sources:[]});
  useEffect(()=>{queueMicrotask(async()=>setData(await queryIntegrationMatrix(getSupabaseBrowserClient())))},[]);
  return <><ModuleHeader eyebrow="GOVERNANÇA" title="Matriz de integração" text="Fontes, hubs, acordos e estágios reais de integração por setor."/><div className="matrix-table"><div className="matrix-head"><span>SETOR</span><span>HUB</span><span>TIPO</span><span>FONTE</span><span>STATUS</span><span>ACORDO</span></div>{data.sectors.map((s:any)=>{const hub=data.hubs.find((h:any)=>h.sector_id===s.id);const source=data.sources.find((x:any)=>x.sector_id===s.id);const agreement=data.agreements.find((a:any)=>a.sector_id===s.id);return <div className="matrix-row" key={s.id}><b>{s.code}</b><span>{hub?.name||"Hub ainda não integrado"}</span><span>{hub?.integration_type||source?.source_type||"—"}</span><span>{source?.name||"Fonte ainda não integrada"}</span><StatusBadge value={source?.status||hub?.status||"EM_IMPLANTACAO"}/><span>{agreement?.status||"Nenhum acordo"}</span></div>})}</div><DataProvenanceReal/></>;
}

export function AgreementsModule() {
  const [data,setData]=useState<any>({agreements:[],hubs:[],sectors:[],sources:[]});
  useEffect(()=>{queueMicrotask(async()=>setData(await queryIntegrationMatrix(getSupabaseBrowserClient())))},[]);
  return <><ModuleHeader eyebrow="GOVERNANÇA" title="Acordos de integração" text="Pactos institucionais, responsabilidades, periodicidade e revisões."/><div className="agreement-grid">{data.agreements.length?data.agreements.map((a:any)=>{const sector=data.sectors.find((s:any)=>s.id===a.sector_id);const hub=data.hubs.find((h:any)=>h.id===a.hub_id);return <article className="agreement-card" key={a.id}><StatusBadge value={a.status}/><h3>{sector?.code||"Regional"} · {hub?.name||"Integração institucional"}</h3><p>{a.notes||"Acordo cadastrado sem observações adicionais."}</p><div><span>Tipo <b>{a.integration_type}</b></span><span>Periodicidade <b>{a.update_frequency||"Não definida"}</b></span><span>Última revisão <b>{a.last_review||"—"}</b></span><span>Próxima revisão <b>{a.next_review||"—"}</b></span></div></article>}):<EmptyState title="Nenhum acordo de integração cadastrado" text="Acordos aparecerão após formalização institucional."/>}</div><DataProvenanceReal/></>;
}

export function AboutModule() {
  return <><ModuleHeader eyebrow="PORTAL COMUNICA!" title="Sobre o RADAR 360" text="Visão Integrada da URE Guarulhos Sul."/><div className="about-grid">{[["Portal Comunica!","Ecossistema que organiza produtos, fluxos e comunicação institucional."],["RADAR 360","Camada de integração, acompanhamento, governança e visão regional."],["BIGuarulhosSul","Camada de inteligência de dados, indicadores e relatórios autorizados."],["Hubs setoriais","Produtos operacionais próprios dos setores, sem duplicação de suas funções."],["Acordos","Governança das integrações, fontes, responsabilidades e níveis de acesso."]].map(x=><article key={x[0]}><span>◆</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className="version-card"><b>RADAR 360</b><span>Versão 1.1 · URE Guarulhos Sul</span></div></>;
}

export function ItemDetailModule({id,user,go}:{id:string;user:User;go:(path:string)=>void}) {
  const [item,setItem]=useState<RadarItem|null>(null);const [history,setHistory]=useState<any[]>([]);const [comments,setComments]=useState<any[]>([]);const [evidences,setEvidences]=useState<any[]>([]);const [note,setNote]=useState("");
  const load=async()=>{const supabase=getSupabaseBrowserClient();const {data}=await supabase.from("institutional_items").select("id,organization_id,sector_id,school_id,category_id,record_type,title,description,status,priority,responsible_user_id,created_by,updated_by,created_at,updated_at,due_date,visibility,source,active,sectors(code,name),schools(name,slug,pei),demand_categories(name)").eq("id",id).maybeSingle();setItem(data as unknown as RadarItem|null);const [{data:h},{data:c},{data:e}]=await Promise.all([supabase.from("institutional_item_history").select("id,event_type,previous_value,new_value,performed_by,created_at").eq("item_id",id).order("created_at",{ascending:false}),supabase.from("institutional_item_comments").select("id,content,visibility,created_at").eq("item_id",id).order("created_at",{ascending:false}),supabase.from("evidences").select("id,title,evidence_type,external_url,created_at").eq("item_id",id).order("created_at",{ascending:false})]);setHistory(h??[]);setComments(c??[]);setEvidences(e??[])};
  useEffect(()=>{queueMicrotask(()=>void load())},[id,user.id]);
  const update=async(field:string,value:string|null)=>{const supabase=getSupabaseBrowserClient();const {data:{user:authUser}}=await supabase.auth.getUser();if(!authUser)return;await supabase.from("institutional_items").update({[field]:value,updated_by:authUser.id}).eq("id",id);await load()};
  const addComment=async(e:React.FormEvent)=>{e.preventDefault();if(!item||!note.trim())return;const supabase=getSupabaseBrowserClient();const {data:{user:authUser}}=await supabase.auth.getUser();if(!authUser)return;await supabase.from("institutional_item_comments").insert({organization_id:item.organization_id,item_id:id,author_id:authUser.id,content:note.trim(),visibility:"GESTAO"});setNote("");await load()};
  if(!item)return <><ModuleHeader eyebrow="ITEM INSTITUCIONAL" title="Registro indisponível" text="O item não existe ou seu perfil não possui acesso."/><EmptyState title="Item não encontrado" text="A RLS não retornou este registro para a sessão atual." action={<button onClick={()=>go("/radar360/itens")}>Voltar</button>}/></>;
  const canEdit=user.role==="ADMIN"||(user.role==="GESTAO"&&user.sectorId===item.sector_id);
  return <><button className="back-link" onClick={()=>go("/radar360/itens")}>← Voltar aos itens</button><ModuleHeader eyebrow={`${item.record_type} · ${item.sectors?.code||"REGIONAL"}`} title={item.title} text={item.description||"Sem descrição adicional."}/><div className="item-detail-grid"><section className="panel item-fields"><h2>Dados do item</h2><div><span>Categoria<b>{item.demand_categories?.name||"—"}</b></span><span>Escola<b>{item.schools?.name||"Regional"}</b></span><span>Status{canEdit?<select value={item.status} onChange={e=>void update("status",e.target.value)}>{["NOVA","EM_ANALISE","EM_ANDAMENTO","AGUARDANDO_ESCOLA","AGUARDANDO_SETOR","AGUARDANDO_ORGAO_CENTRAL","CONCLUIDA","SUSPENSA","CANCELADA"].map(x=><option key={x}>{x}</option>)}</select>:<b>{item.status}</b>}</span><span>Prioridade{canEdit?<select value={item.priority} onChange={e=>void update("priority",e.target.value)}>{["BAIXA","NORMAL","ALTA","CRITICA"].map(x=><option key={x}>{x}</option>)}</select>:<b>{item.priority}</b>}</span><span>Prazo{canEdit?<input type="date" value={item.due_date||""} onChange={e=>void update("due_date",e.target.value||null)}/>:<b>{item.due_date||"—"}</b>}</span><span>Visibilidade<b>{item.visibility}</b></span><span>Fonte<b>{item.source||"RADAR 360"}</b></span></div></section><section className="panel"><h2>Evidências</h2>{evidences.length?<div className="simple-list">{evidences.map(x=><div key={x.id}><b>{x.title}</b><span>{x.evidence_type}</span></div>)}</div>:<EmptyState title="Nenhuma evidência" text="Ainda não há evidências vinculadas a este item."/>}</section></div><div className="item-detail-grid"><section className="panel"><h2>Histórico</h2>{history.length?<div className="timeline">{history.map(x=><div key={x.id}><i/><p><b>{x.event_type.replaceAll("_"," ")}</b><span>{new Date(x.created_at).toLocaleString("pt-BR")}</span></p></div>)}</div>:<EmptyState title="Sem histórico" text="As alterações futuras aparecerão aqui."/>}</section><section className="panel"><h2>Comentários e devolutivas</h2>{comments.length?<div className="simple-list">{comments.map(x=><div key={x.id}><span>{x.content}</span><small>{new Date(x.created_at).toLocaleString("pt-BR")}</small></div>)}</div>:<EmptyState title="Nenhuma devolutiva" text="Registre um comentário institucional quando necessário."/>}{user.role!=="VISITANTE"&&<form className="comment-form" onSubmit={addComment}><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Registrar devolutiva..." required/><button>Adicionar</button></form>}</section></div><DataProvenanceReal/></>;
}
