"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import { useEffect, useState } from "react";
import type { User } from "../types";
import { getSupabaseBrowserClient } from "../lib/supabase/client";
import { ATTENTION_LEVELS, EXPERIENCE_DIMENSIONS, parseExperienceCsv, prepareExperienceImport } from "../lib/school-experience.mjs";
import { AlertBanner, DataTable, EmptyState, FilterBar, LoadingState, MetricCard, PageHeader, SearchInput, SectionHeader, StatusBadge } from "./SuperBIUI";

export type ExperienceMetric = {
  id:string; school_id:string; reference_period:string; source:string; average_score:number; attention_score:number;
  base_attention_level:string; attention_level:string; critical_dimension:string; critical_dimension_score:number;
  best_dimension:string; best_dimension_score:number; trigger_count:number; below_3_count:number; below_4_count:number;
  below_5_count:number; below_6_count:number; attention_reasons:Array<{key:string;label:string;score:number;severity:string}>;
  class_quality:number; school_climate:number; spaces_and_bathrooms:number; learning_support:number;
  engagement_life_project:number; overall_satisfaction:number; schools?:{name?:string;slug?:string}|null;
};

const levelLabel = (value:string) => ATTENTION_LEVELS.find((level) => level.value === value)?.label ?? value;
const dimensionLabel = (value:string) => EXPERIENCE_DIMENSIONS.find((dimension) => dimension.key === value)?.label ?? value;
const number = (value:number) => Number(value).toLocaleString("pt-BR", { minimumFractionDigits:1, maximumFractionDigits:1 });
const levelRank = (value:string) => ATTENTION_LEVELS.find((level) => level.value === value)?.rank ?? 0;
const badgeTone = (value:string) => value === "FAVORAVEL" ? "success" as const : value === "REGULAR" ? "info" as const : value === "ATENCAO" || value === "ELEVADA" ? "warning" as const : "danger" as const;
const heatClass = (value:number) => value < 3 ? "is-critical" : value < 5 ? "is-elevated" : value < 6 ? "is-watch" : value >= 8 ? "is-favorable" : "is-neutral";

function ImportPanel({ onImported }:{onImported:()=>Promise<void>}) {
  const [period,setPeriod]=useState(""); const [source,setSource]=useState("Pesquisa de Experiência Escolar");
  const [report,setReport]=useState<any|null>(null); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const selectFile=async(event:React.ChangeEvent<HTMLInputElement>)=>{
    const file=event.target.files?.[0]; if(!file)return; setMessage("");
    try{
      const supabase=getSupabaseBrowserClient(); const {data:schoolRows,error}=await supabase.from("schools").select("id,name,organization_id").eq("active",true);
      if(error)throw error; const rows=parseExperienceCsv(await file.text()); setReport(prepareExperienceImport(rows,schoolRows??[],{referencePeriod:period,source}));
    }catch(error){setReport(null);setMessage(error instanceof Error?error.message:"Não foi possível analisar o arquivo.")}
  };
  const importRows=async()=>{
    if(!report?.accepted.length)return;setSaving(true);setMessage("");const supabase=getSupabaseBrowserClient();const {data:{user}}=await supabase.auth.getUser();
    if(!user){setMessage("Sessão administrativa indisponível.");setSaving(false);return}
    const payload=report.accepted.map((row:any)=>({...row,imported_by:user.id}));
    const {error}=await supabase.from("school_experience_metrics").insert(payload);
    if(error)setMessage("Importação recusada. Confirme migration, RLS e se a mesma escola, período e fonte já foram importados.");else{setMessage(`${payload.length} registros importados com associação institucional.`);await onImported()};setSaving(false);
  };
  return <section className="experience-import superbi-card"><SectionHeader title="Importação controlada" description="CSV com Escola e seis dimensões. Nenhuma escola desconhecida é criada."/>
    <div className="experience-import-fields"><label>Período<input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="2026-1" pattern="[0-9]{4}(-[1-4])?"/></label><label>Fonte<input value={source} onChange={e=>setSource(e.target.value)} required/></label><label className="experience-file">Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={e=>void selectFile(e)} disabled={!period||!source.trim()}/></label></div>
    {message&&<AlertBanner tone={message.includes("importados")?"success":"danger"}>{message}</AlertBanner>}
    {report&&<><div className="experience-import-report"><span><strong>{report.received}</strong> recebidos</span><span><strong>{report.matched}</strong> associados</span><span><strong>{report.notFound}</strong> não encontrados</span><span><strong>{report.duplicates}</strong> duplicidades</span><span><strong>{report.invalid}</strong> inválidos</span><span><strong>{report.pending.length}</strong> pendências</span></div>{report.pending.length?<DataTable><caption>Pendências da importação</caption><thead><tr><th>Linha</th><th>Nome recebido</th><th>Inconsistência</th></tr></thead><tbody>{report.pending.map((item:any)=><tr key={`${item.row}-${item.schoolName}`}><td>{item.row}</td><td>{item.schoolName||"—"}</td><td>{item.errors.join(" ")}</td></tr>)}</tbody></DataTable>:<AlertBanner tone="success">Todas as escolas foram associadas com segurança.</AlertBanner>}<button className="experience-primary" onClick={()=>void importRows()} disabled={saving||!report.accepted.length}>{saving?"Importando…":`Importar ${report.accepted.length} registros válidos`}</button></>}
  </section>;
}

export function SchoolExperienceSummary({schoolId}:{schoolId:string}) {
  const [metric,setMetric]=useState<ExperienceMetric|null>(null);const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;void getSupabaseBrowserClient().from("school_experience_metrics").select("*").eq("school_id",schoolId).order("reference_period",{ascending:false}).limit(1).maybeSingle().then(({data})=>{if(active){setMetric(data as ExperienceMetric|null);setLoading(false)}});return()=>{active=false}},[schoolId]);
  if(loading)return <LoadingState title="Carregando experiência escolar…"/>;
  if(!metric)return <section className="experience-school-section"><SectionHeader title="Experiência Escolar" description="Índice de Atenção à Experiência Escolar"/><EmptyState title="Nenhuma edição disponível" description="A seção será preenchida após uma importação institucional validada."/></section>;
  return <section className="experience-school-section"><SectionHeader title="Experiência Escolar" description={`Período ${metric.reference_period} · instrumento de priorização e acompanhamento`}/><div className="experience-school-metrics"><MetricCard label="Média geral" value={number(metric.average_score)} detail="Escala de 0 a 10" tone="teal"/><MetricCard label="Índice de Atenção" value={number(metric.attention_score)} detail="Escala de 0 a 100" tone="amber"/><MetricCard label="Nível" value={levelLabel(metric.attention_level)} detail={`${metric.trigger_count} sinais de atenção`} tone="blue"/></div><div className="experience-dimension-grid">{EXPERIENCE_DIMENSIONS.map(item=><article key={item.key}><span>{item.label}</span><strong>{number(metric[item.key as keyof ExperienceMetric] as number)}</strong></article>)}</div><div className="experience-school-highlights"><span><small>Principal atenção</small><strong>{dimensionLabel(metric.critical_dimension)}</strong></span><span><small>Resultado mais favorável</small><strong>{dimensionLabel(metric.best_dimension)}</strong></span></div><section className="experience-reasons"><h3>Motivos de Atenção</h3>{metric.attention_reasons.length?<ul>{metric.attention_reasons.map(reason=><li key={reason.key}><span><strong>{reason.label}</strong><small>{reason.severity.replaceAll("_"," ")}</small></span><b>{number(reason.score)}</b></li>)}</ul>:<p>Nenhuma dimensão abaixo do limite inicial de acompanhamento.</p>}</section></section>;
}

export default function SchoolExperience360({user,go}:{user:User;go:(path:string)=>void}) {
  const [metrics,setMetrics]=useState<ExperienceMetric[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [query,setQuery]=useState("");const [period,setPeriod]=useState("");const [level,setLevel]=useState("");const [dimension,setDimension]=useState("");const [trigger,setTrigger]=useState("");const [sort,setSort]=useState("attention");
  const [averageMin,setAverageMin]=useState("");const [averageMax,setAverageMax]=useState("");
  const load=async()=>{setLoading(true);setError("");const {data,error:loadError}=await getSupabaseBrowserClient().from("school_experience_metrics").select("*,schools(name,slug)").order("reference_period",{ascending:false});if(loadError)setError("Os dados ainda não estão disponíveis. Confirme a aplicação da migration e as permissões do perfil.");setMetrics((data??[]) as unknown as ExperienceMetric[]);setLoading(false)};
  useEffect(()=>{queueMicrotask(()=>void load())},[user.id]);
  const periods=[...new Set(metrics.map(item=>item.reference_period))].sort().reverse();const selectedPeriod=period||periods[0]||"";
  const current=[...metrics.filter(item=>item.reference_period===selectedPeriod&&(!query||(item.schools?.name??"").toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))&&(!level||item.attention_level===level)&&(!dimension||item.critical_dimension===dimension)&&(!trigger||(trigger==="yes"?item.trigger_count>0:item.trigger_count===0))&&(!averageMin||Number(item.average_score)>=Number(averageMin))&&(!averageMax||Number(item.average_score)<=Number(averageMax)))].sort((a,b)=>sort==="average"?a.average_score-b.average_score:sort==="name"?(a.schools?.name??"").localeCompare(b.schools?.name??"","pt-BR"):sort.startsWith("dimension:")?Number(a[sort.split(":")[1] as keyof ExperienceMetric])-Number(b[sort.split(":")[1] as keyof ExperienceMetric]):levelRank(b.attention_level)-levelRank(a.attention_level)||b.below_3_count-a.below_3_count||b.attention_score-a.attention_score);
  const periodRows=metrics.filter(item=>item.reference_period===selectedPeriod);const regionalAverage=periodRows.length?periodRows.reduce((sum,item)=>sum+Number(item.average_score),0)/periodRows.length:0;const regionalAttention=periodRows.length?periodRows.reduce((sum,item)=>sum+Number(item.attention_score),0)/periodRows.length:0;
  const counts=Object.fromEntries(ATTENTION_LEVELS.map(item=>[item.value,periodRows.filter(row=>row.attention_level===item.value).length]));
  const history=[...periods].reverse().map((historyPeriod)=>{const rows=metrics.filter(item=>item.reference_period===historyPeriod);const dimensions=Object.fromEntries(EXPERIENCE_DIMENSIONS.map(item=>[item.key,rows.reduce((sum,row)=>sum+Number(row[item.key as keyof ExperienceMetric]),0)/rows.length]));return {period:historyPeriod,average:rows.reduce((sum,row)=>sum+Number(row.average_score),0)/rows.length,attention:rows.reduce((sum,row)=>sum+Number(row.attention_score),0)/rows.length,dimensions}});
  const delta=(value:number,previous:number|undefined)=>previous===undefined?"—":`${value-previous>=0?"+":""}${number(value-previous)}`;
  return <div className="experience-page superbi-ui"><PageHeader eyebrow="EVIDÊNCIAS · ACOMPANHAMENTO REGIONAL" title="Experiência Escolar 360" description="Leitura explicável das seis dimensões da pesquisa escolar, sem caráter punitivo."/>
    {error&&<AlertBanner tone="danger">{error}</AlertBanner>}{user.role==="ADMIN"&&<ImportPanel onImported={load}/>} {loading?<LoadingState title="Consolidando experiência escolar…"/>:!periodRows.length?<EmptyState title="Nenhuma edição importada" description="Importe uma base validada para iniciar a análise. Nenhum dado demonstrativo foi criado."/>:<>
    <FilterBar><SearchInput value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar escola…"/><label>Período<select value={selectedPeriod} onChange={e=>setPeriod(e.target.value)}>{periods.map(item=><option key={item}>{item}</option>)}</select></label><label>Nível<select value={level} onChange={e=>setLevel(e.target.value)}><option value="">Todos</option>{ATTENTION_LEVELS.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Dimensão crítica<select value={dimension} onChange={e=>setDimension(e.target.value)}><option value="">Todas</option>{EXPERIENCE_DIMENSIONS.map(item=><option value={item.key} key={item.key}>{item.label}</option>)}</select></label><label>Gatilhos<select value={trigger} onChange={e=>setTrigger(e.target.value)}><option value="">Todos</option><option value="yes">Com gatilho</option><option value="no">Sem gatilho</option></select></label><label>Média mínima<input type="number" min="0" max="10" step="0.1" value={averageMin} onChange={e=>setAverageMin(e.target.value)}/></label><label>Média máxima<input type="number" min="0" max="10" step="0.1" value={averageMax} onChange={e=>setAverageMax(e.target.value)}/></label></FilterBar>
    <section className="experience-kpis"><MetricCard label="Média regional" value={number(regionalAverage)} detail="Escala de 0 a 10" tone="teal"/><MetricCard label="Índice de Atenção médio" value={number(regionalAttention)} detail="Escala de 0 a 100" tone="amber"/><MetricCard label="Escolas avaliadas" value={periodRows.length} detail={`Período ${selectedPeriod}`} tone="cyan"/><MetricCard label="Gatilhos críticos" value={periodRows.filter(row=>row.below_3_count>0).length} detail="Ao menos uma dimensão abaixo de 3" tone="amber"/></section>
    <section className="experience-section"><SectionHeader title="Distribuição dos níveis de atenção" description="Quantidade de escolas em cada faixa resultante."/><div className="experience-levels">{ATTENTION_LEVELS.map(item=><article key={item.value}><StatusBadge tone={badgeTone(item.value)}>{item.label}</StatusBadge><strong>{counts[item.value]}</strong></article>)}</div></section>
    <section className="experience-section"><SectionHeader title="Seis dimensões regionais" description="Médias e quantidade de escolas abaixo de 6. Histórico só aparece quando houver outra edição."/><div className="experience-regional-dimensions">{EXPERIENCE_DIMENSIONS.map(item=>{const average=periodRows.reduce((sum,row)=>sum+Number(row[item.key as keyof ExperienceMetric]),0)/periodRows.length;const below=periodRows.filter(row=>Number(row[item.key as keyof ExperienceMetric])<6).length;return <article key={item.key}><span>{item.label}</span><strong>{number(average)}</strong><small>{below} escolas abaixo de 6</small><em>{periods.length>1?"Comparação disponível por período":"Histórico ainda não disponível"}</em></article>})}</div></section>
    <section className="experience-section"><SectionHeader title="Matriz Escola × Dimensão" description="Valores numéricos complementam a escala visual e não dependem exclusivamente da cor." action={<label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option value="attention">Índice de Atenção</option><option value="average">Média</option><option value="name">Nome</option>{EXPERIENCE_DIMENSIONS.map(item=><option value={`dimension:${item.key}`} key={item.key}>{item.label}</option>)}</select></label>}/><DataTable className="experience-heatmap"><caption>Matriz das seis dimensões por escola</caption><thead><tr><th>Escola</th>{EXPERIENCE_DIMENSIONS.map(item=><th key={item.key} title={item.label}>{item.label}</th>)}<th>Índice</th></tr></thead><tbody>{current.map(row=><tr key={row.id}><th scope="row">{row.schools?.name}</th>{EXPERIENCE_DIMENSIONS.map(item=>{const value=Number(row[item.key as keyof ExperienceMetric]);return <td key={item.key} className={heatClass(value)} aria-label={`${item.label}: ${number(value)}`}>{number(value)}</td>})}<td><strong>{number(row.attention_score)}</strong></td></tr>)}</tbody></DataTable></section>
    <section className="experience-section"><SectionHeader title="Prioridades de Acompanhamento" description="Ordenação explicável por prioridade resultante, gatilhos críticos e Índice de Atenção."/><div className="experience-priorities">{current.slice(0,20).map(row=><article key={row.id}><div><h3>{row.schools?.name}</h3><StatusBadge tone={badgeTone(row.attention_level)}>{levelLabel(row.attention_level)}</StatusBadge></div><dl><div><dt>Média</dt><dd>{number(row.average_score)}</dd></div><div><dt>Índice</dt><dd>{number(row.attention_score)}</dd></div><div><dt>Principal atenção</dt><dd>{dimensionLabel(row.critical_dimension)} · {number(row.critical_dimension_score)}</dd></div><div><dt>Gatilhos</dt><dd>{row.trigger_count}</dd></div></dl><button onClick={()=>go(`/radar360/escolas/${row.schools?.slug}`)}>Abrir Escola 360 <span aria-hidden="true">→</span></button></article>)}</div></section>
    <section className="experience-section"><SectionHeader title="Principais Sinais Regionais" description="Contagens calculadas exclusivamente a partir da edição importada."/><div className="experience-signals">{EXPERIENCE_DIMENSIONS.map(item=><article key={item.key}><h3>{item.label}</h3>{[6,5,4,3].map(limit=>{const count=periodRows.filter(row=>Number(row[item.key as keyof ExperienceMetric])<limit).length;return <p key={limit}><strong>{count}</strong> escolas ({number(count/periodRows.length*100)}%) abaixo de {limit}</p>})}</article>)}</div></section>
    {history.length>1&&<section className="experience-section"><SectionHeader title="Evolução regional por edição" description="Variações descritivas em relação à edição anterior, sem inferência de causalidade."/><DataTable><caption>Histórico das médias regionais e variações absolutas</caption><thead><tr><th>Período</th><th>Média</th><th>Δ média</th><th>Índice</th><th>Δ índice</th>{EXPERIENCE_DIMENSIONS.map(item=><th key={item.key}>{item.label}</th>)}</tr></thead><tbody>{history.map((item,index)=><tr key={item.period}><th scope="row">{item.period}</th><td>{number(item.average)}</td><td>{delta(item.average,history[index-1]?.average)}</td><td>{number(item.attention)}</td><td>{delta(item.attention,history[index-1]?.attention)}</td>{EXPERIENCE_DIMENSIONS.map(dimension=><td key={dimension.key}>{number(Number(item.dimensions[dimension.key]))} <small>({delta(Number(item.dimensions[dimension.key]),history[index-1]?Number(history[index-1].dimensions[dimension.key]):undefined)})</small></td>)}</tr>)}</tbody></DataTable></section>}
    <section className="experience-section"><SectionHeader title="Tabela detalhada" description={`${current.length} escolas conforme os filtros ativos.`}/><DataTable><caption>Detalhamento do Índice de Atenção à Experiência Escolar</caption><thead><tr><th>Escola</th><th>Período</th><th>Média</th><th>Índice</th><th>Classificação base</th><th>Prioridade resultante</th><th>Dimensão crítica</th><th>Melhor dimensão</th><th>Gatilhos</th></tr></thead><tbody>{current.map(row=><tr key={row.id}><th scope="row">{row.schools?.name}</th><td>{row.reference_period}</td><td>{number(row.average_score)}</td><td>{number(row.attention_score)}</td><td>{levelLabel(row.base_attention_level)}</td><td>{levelLabel(row.attention_level)}</td><td>{dimensionLabel(row.critical_dimension)} · {number(row.critical_dimension_score)}</td><td>{dimensionLabel(row.best_dimension)} · {number(row.best_dimension_score)}</td><td>{row.trigger_count}</td></tr>)}</tbody></DataTable></section>
    <AlertBanner tone="info">{periods.length===1?"Uma única edição disponível. Não são exibidas tendências ou evolução fictícias.":"Há múltiplas edições disponíveis; use o filtro de período para comparação descritiva."}</AlertBanner>
    </>}</div>;
}
