import type { School } from "../types";

const rawSchools = [
  "AGOSTINHO CANO","ALAYDE MARIA VICENTE PROFA","ALBERTO BACAN PROF - PEI","ALBERTO MENDES JR CAP PM - PEI",
  "ALEXANDRE LOPES OLIVEIRA - PEI","ALICE CHUERY PROFA - PEI","ANNA LAMBERGA ZEGLIO","ANTONIO DE RE VEREADOR",
  "ANTONIO PRATICI PREFEITO","ANTONIO VIANA DE SOUZA PROF","ARY GOMES CEL - PEI","AUGUST JOHANNES FERDINANDUS STAUDER, PADRE - PEI",
  "BARTHOLOMEU DE CARLOS - PEI","BRUNO RICCO PADRE - PEI","CACILDA CACAPAVA DE OLIVEIRA PROFA","CAPISTRANO DE ABREU",
  "CARLOS MACHADO BITENCOURT MAL - PEI","CID AUGUSTO GUELLI PROF","CIDADE SOIMCO II - PEI","CLARICE LISPECTOR",
  "CONJUNTO HAB. BAIRRO DOS PIMENTAS II - PEI","CONSELHEIRO CRISPINIANO - PEI","EMILIA ANNA ANTONIO PROFA","ENNIO CHIESA PROF - PEI",
  "ERICO VERISSIMO - PEI","FABIO FANUCCHI PROF - PEI","FRANCISCA BATISTA TRINDADE PROFA","FREDERICO DE BARROS BROTERO PROF",
  "GUILHERMINO RODRIGUES DE LIMA - PEI","HOMERO RUBENS DE SA PROF - PEI","HUGO DE AGUIAR","INOCOOP II - PEI",
  "IZABEL FERREIRA DOS SANTOS PROFA - PEI","JAIR MIRANDA DR","JARDIM ARUJÁ - PEI","JD MARIA DIRCE III",
  "JD NOVA CUMBICA II - PEI","JOAO ALVARES DE SIQUEIRA BUENO","JOAO CAVALHEIRO SALEM PROF","JOAO CRISPINIANO SOARES",
  "JOAO DE ALMEIDA BARBOSA","JOAO NUNES PASTOR","JOAO RIBEIRO DE BARROS COMANDANTE","JOCILA PEREIRA GUIMARAES PROFA - PEI",
  "JOSE ALVES DE CERQUEIRA CESAR - PEI","JOSE DA COSTA BOUCINHAS PROF - PEI","JOSE ROBERTO FRIEBOLIN PROF - PEI","JOSE SCARAMELLI PROF - PEI",
  "LAR IRMA CELESTE","LAURA DA PURIFICACAO C.MENDES PROFA - PEI","LEVI VIEIRA DA MAIA, PROF - PEI","LICINIO CARPINELLI PROF",
  "LINDAMIL BARBOSA DE OLIVEIRA PROFA","LOUIS BRAILLE - PEI","MARIA APARECIDA FELIX PORTO PROFA","MARIA APARECIDA RODRIGUES PROFA",
  "MARIA HILDA ORNELAS DE OLIVEIRA PROFA - PEI","MARIA LEDA FERNANDES BRIGO PROFA","MARINHA FERR. DO NASCIMENTO PROFA","MARIO NAKATA PROF",
  "MAURICIO GOULART DEPUTADO - PEI","ORLANDO MINELLA - PEI","OSWALDO SAMPAIO ALVES - PEI","PARQUE JUREMA III",
  "PARQUE JUREMA IV - PEI","PASCOAL MAIMONI FILHO PROF - PEI","PAULO NOGUEIRA PROF - PEI","PAULO ROLIM LOUREIRO DOM - PEI",
  "PEDRO MORCELI","PIMENTAS VII - PEI","RAFAEL RODRIGUES FILHO,PREF","REPUBLICA DA VENEZUELA",
  "REPÚBLICA DA VENEZUELA II - PEI","ROBERTO HIPOLITO DA COSTA BRIG.AR - PEI","ROTARY","SEBASTIAO WALTER FUSCO",
  "THEREZINHA CLOSA ELEUTERIO PROFA - PEI","VALENTIN GONZALEZ ALONSO PADRE - PEI","VICENTE MELRO - PEI","VICTOR CIVITA - PEI",
  "WALDEMAR FREIRE VERAS VEREADOR","ZILDA ROMEIRO PINTO MOREIRA DA SILVA, PROFA",
];

const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
  .replace(/\s*-\s*pei$/i, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const schools: School[] = rawSchools.map((raw, index) => ({
  id: `school-${String(index + 1).padStart(3, "0")}`,
  name: raw.replace(/\s*-\s*PEI$/i, ""),
  slug: slugify(raw),
  pei: /-\s*PEI$/i.test(raw),
  status: "ativa",
}));
