import type { Sector } from "../types";

const access = ["ADMIN", "GESTAO", "VISITANTE"] as const;
const make = (shortName: string, name: string, description: string, menu: string[], status: Sector["status"] = "Em implantação", hubUrl?: string): Sector => ({
  id: shortName.toLowerCase(), slug: shortName.toLowerCase(), name, shortName, group: "URE Guarulhos Sul",
  description, icon: shortName.slice(0, 2), status, integrationType: hubUrl ? "Link externo" : status === "Integrado" ? "Dashboard" : "Planejada",
  hubUrl, visibility: [...access], menu,
});
const common = ["Visão Geral", "Demandas", "Acompanhamento", "Documentos", "Histórico", "Fontes de Dados", "Evidências"];

export const sectors: Sector[] = [
  make("GAB", "Gabinete da Dirigente Regional de Ensino", "Direção estratégica, articulação institucional e tomada de decisão.", ["Visão Geral","Agenda Estratégica","Ações Prioritárias","Indicadores","Comunicados","Documentos"], "Parcialmente integrado"),
  make("ASURE", "Assessoria Técnica", "Apoio direto à gestão, planejamento, articulação e modernização institucional.", ["Visão Geral","Plano de Trabalho da URE","Planejamento Estratégico","Projetos e Programas","Demandas da Dirigente","Indicadores Gerenciais","Relatórios Institucionais","Processos e Expedientes","Contratos e Convênios – Acompanhamento","Transformação Digital","Gestão do Conhecimento","Agenda Institucional","Autoridades e Visitas","Demandas Judiciais","Documentos"]),
  make("ESE", "Equipe de Supervisão de Ensino", "Supervisão, regularidade, orientação e acompanhamento das unidades escolares.", ["Visão Geral","Escolas por Supervisor","Visitas de Supervisão","Plano de Acompanhamento","Apoio Presencial","Processos Educacionais","Regularidade das Escolas","Autorizações e Funcionamento","Documentos Escolares","Orientações","Programas e Projetos","Comissões e Apurações","Evidências","Devolutivas","Pendências","Histórico por Escola"], "Link externo"),
  make("EEC", "Equipe de Especialistas em Currículo", "Currículo, formação continuada e apoio pedagógico às escolas.", ["Visão Geral","Currículo","Formação Continuada","Programas e Projetos","Acompanhamento Pedagógico","Apoio Presencial às Escolas","Materiais Didáticos","Avaliações","Indicadores Educacionais","Resultados de Aprendizagem","Planos de Melhoria","Salas de Leitura","Educação Especial e Inclusão","Reuniões Pedagógicas","Formações Realizadas","Agenda de Formação","Evidências Pedagógicas"]),
  make("SEINTEC", "Serviço de Informações Educacionais e Tecnologia", "Informações educacionais, avaliações, tecnologia e governança digital.", ["Visão Geral","Avaliações","Provas e Aplicações","Tecnologia Educacional","Inclusão Digital","Ambientes Tecnológicos","Plataformas Educacionais","Indicadores","Coletas","Bases de Dados","Escolas","Projetos","Acompanhamentos","Evidências","Orientações","Painéis","Governança Digital"], "Parcialmente integrado"),
  make("SETEC", "Seção de Tecnologia", "Operação tecnológica, suporte, conectividade e saúde digital das escolas.", ["Painel Operacional","Chamados","Apoio ao Usuário","Escolas","Equipamentos","Inventário","Conectividade","Wi-Fi","LAN","Access Points","SD-WAN","Infraestrutura de Rede","Manutenção","Field Service","Visitas Técnicas","PROATI","Plataformas","Evidências","Indicadores","Saúde Tecnológica das Escolas"], "Link externo"),
  make("SEGRE", "Serviço de Gestão da Rede Escolar", "Planejamento, atendimento e organização da rede escolar.", ["Visão Geral","Rede Escolar","Demanda Escolar","Vagas","Matrículas","Vida Escolar","Censo Escolar","Cadastro de Escolas","Criação de Escolas","Expansão da Rede","Municipalização","Planejamento de Atendimento","Escolas","Indicadores","Orientações"]),
  make("SEMAT", "Seção de Matrícula", "Matrículas, formação de classes, demanda e capacidade de atendimento.", ["Visão Geral","Matrículas","Formação de Classes","Demanda por Vagas","Transferências","Atendimento Escolar","Capacidade de Atendimento","Expansão da Rede","Novas Escolas","Municipalização","Escolas","Indicadores","Orientações","Pendências"]),
  make("SEVESC", "Seção de Vida Escolar", "Registros, documentos, concluintes e regularização da vida escolar.", ["Visão Geral","Vida Escolar","Registros Escolares","Históricos Escolares","Certificados","Diplomas","Concluintes","Educação de Jovens e Adultos","Regularização de Vida Escolar","Documentação Escolar","Arquivo de Escolas","Escolas Extintas","Orientações","Pendências","Processos"]),
  make("SEPES", "Serviço de Pessoas", "Gestão de pessoas com indicadores agregados e proteção de dados pessoais.", ["Visão Geral","Gestão de Pessoas","Administração de Pessoal","Frequência e Pagamento","Desenvolvimento Profissional","Atribuição de Classes e Aulas","Absenteísmo","Vagas","Readaptação","Indicadores de Pessoal","Orientações","Processos","Escolas"]),
  make("SEAPE", "Seção de Administração de Pessoal", "Rotinas, movimentações e processos funcionais.", ["Visão Geral","Administração de Pessoal","Atribuição de Classes e Aulas","Absenteísmo","Vagas","Readaptação","Movimentações","Processos Funcionais","Rotinas de Pessoal","Pendências","Indicadores","Orientações"]),
  make("SEFREP", "Seção de Frequência e Pagamento", "Frequência, folha e ocorrências, sob permissões específicas.", ["Visão Geral","Frequência","Pagamento","Folha de Pagamento","Inclusões em Folha","Ocorrências","Pendências","Processos","Orientações","Indicadores"]),
  make("SEAFIN", "Serviço de Administração e Finanças", "Apoio administrativo, gestão documental, compras e finanças.", ["Visão Geral","Apoio Administrativo às Escolas","Gestão Financeira","Gestão Documental","Processos","Protocolo","Expedientes","Arquivo","Correspondências","Contratos","Convênios","Compras","Serviços","Prestação de Contas","Indicadores","Pendências"]),
  make("SEFIN", "Seção de Finanças", "Execução financeira, repasses, prestação de contas e controle.", ["Visão Geral","Execução Financeira","Adiantamentos","Prestação de Contas","APM","Repasses Estaduais","Repasses Federais","Contratos e Convênios","Parcelamentos","Notificações","Órgãos de Controle","Pareceres","Pendências","Indicadores"]),
  make("SECOMSE", "Seção de Compras e Serviços", "Compras, contratos, serviços, estoque e distribuição.", ["Visão Geral","Compras","Licitações","Termos de Referência","Contratos","Convênios","Fornecedores","Serviços","Alimentação Escolar","Transporte Escolar","Segurança","Materiais","Estoque","Distribuição","Recebimentos","Inventário de Estoque","Consumo","Pendências","Indicadores"]),
  make("SEOM", "Serviço de Obras e Manutenção Escolar", "Obras, manutenção, infraestrutura e patrimônio escolar.", ["Visão Geral","Obras","Manutenções","Reformas","Adequações","Plano de Obras","Demandas das Escolas","Infraestrutura Escolar","Patrimônio","Inventário Patrimonial","Bens Inservíveis","Cadastro Físico das Escolas","Dependências","Metragens","Utilização dos Espaços","Escolas","Pendências","Indicadores","Evidências"], "Link externo"),
  make("SEFISC", "Seção de Fiscalização", "Fiscalização de contratos, serviços, obras, utilidades e patrimônio.", ["Visão Geral","Fiscalização de Contratos","Serviços Terceirizados","Obras","Reformas","Manutenção","Inspeções","Utilidades Públicas","Água","Energia","Zeladoria","Limpeza","Copa","Patrimônio","Frota","Transporte Interno","Evidências","Pendências","Indicadores"]),
];

export const genericSectorMenu = common;
